// This file was generated by Prisma.
// In production (e.g. Render), environment variables are injected by the platform.
// Locally, dotenv may be installed to load variables from a .env file.
// Make dotenv optional so Prisma commands don't fail when it's not installed.
try {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  require('dotenv/config');
} catch {
  // ignore if dotenv is not installed
}
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
